# Unified realbot configuration file
# Contains all configuration including constants

# System constants
constants:
  # Vehicle center to steer axis (m) - Kinova / Franka
  vehicle:
    h_x: [0.190150, 0.190150, -0.190150, -0.190150]  # [1.0, 1.0, -1.0, -1.0] * 0.190150
    h_y: [-0.170150, 0.170150, 0.170150, -0.170150]  # [-1.0, 1.0, 1.0, -1.0] * 0.170150
  
  # Encoder magnet offsets
  encoder_magnet_offsets: [-0.4943847656, -0.3540039063, -0.1015625, 0.2856445313]  # [-2023.0/4096, -1450.0/4096, -416.0/4096, 1170.0/4096]
  
  # Control frequencies
  control_freq: 250      # 250 Hz for base control
  control_period: 0.004  # 4 ms (1.0 / 250)
  num_casters: 4

# Camera configuration
cameras:
  # Camera list
  left:
    name: left
    type: realsense
    serial: "336222070065"
    frame_width: 640
    frame_height: 480
    fps: 30
  right:
    name: right
    type: realsense
    serial: "336222076797"
    frame_width: 640
    frame_height: 480
    fps: 30

# Arm configuration
arm:
  ip: "172.16.0.2"
  urdf_path: "./assets/franka.urdf"
  ee_link_name: "panda_hand_tcp"
  policy_frequency: 20
  observe: false
  
  # Joint configuration
  # home_qpos: [0, -0.785, 0, -2.356, 0, 1.571, 0.785]  # leaning back
  home_qpos: [0.0, 0.0, 0.0, -1.6, 0.0, 1.6, 0.8]
  joint_velocity_limit: [2.1750, 2.1750, 2.1750, 2.1750, 2.6100, 2.6100, 2.6100]  # default
  joint_acceleration_limit: [15.0, 7.5, 10.0, 12.5, 15.0, 20.0, 20.0] # default
  joint_jerk_limit: [7500, 3750, 5000, 6250, 7500, 10000, 10000]  # default
  
  # Control factors
  velocity_factor: 0.05
  acceleration_factor: 0.01
  jerk_factor: 0.1
  
  # Joint limits [min, max] for each joint
  joint_limits:
    - [-2.8973, 2.8973]   # Joint 1
    - [-1.8326, 1.8326]   # Joint 2
    - [-2.8972, 2.8972]   # Joint 3
    - [-3.0718, -0.1222]  # Joint 4
    - [-2.8798, 2.8798]   # Joint 5
    - [0.4363, 4.6251]    # Joint 6
    - [-3.0543, 3.0543]   # Joint 7
  
  # Workspace limits
  workspace_limits:
    x: [0, 0.75]
    y: [-0.52, 0.52]
    z: [-0.2, 0.65]
  
# RPC configuration
rpc:
  # Base RPC
  base:
    host: "0.0.0.0"
    port: 10000
    authkey: "secret password"
  
  # Arm RPC
  arm:
    host: "0.0.0.0"
    port: 10001
    authkey: "secret password"
  
  # Server RPC
  server:
    host: "localhost"
    port: 5555
    authkey: "secret password"
